FROM google/nodejs

MAINTAINER  Christopher Lyth <cjlyth@gmail.com>

ENV NPM_CONFIG_USER 1000
ENV NPM_CONFIG_GROUP 1000

ENV NPM_CONFIG_UNSAFE_PERM false

ENV NPM_CONFIG_PARSEABLE true
ENV NPM_CONFIG_IGNORE_SCRIPTS true

ENV NPM_CONFIG_YES true

ENV CI true

ENV BOWER_ALLOW_ROOT true

ENV BOWER_LOG_LEVEL debug
ENV NPM_CONFIG_LOGLEVEL error

# ENV NPM_CONFIG_NPAT false
# ENV NPM_CONFIG_LINK true

WORKDIR /data
ENTRYPOINT ["/usr/bin/env", "npm"]
CMD ["update"]
